import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './_components/layouts/Header'
import MenuNavigate from './_components/layouts/MenuNavigate'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pizza 4Ps',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <MenuNavigate />
        {children}
      </body>
    </html>
  )
}
